---
version: '3.1'

services:

  formalms:
    image: nicholaswilde/formalms:2.3.0.2-ls1
    restart: always
    ports:
      - 8080:80
    volumes:
      - formalms:/var/www/html/formalms
    environment:
      - PUID=1001
      - GUID=1001

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: formalms
      MYSQL_USER: formalms
      MYSQL_PASSWORD: formalms
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
      - ./config:/etc/mysql/conf.d

volumes:
  db:
  formalms:
